@startuml
title Create Room 
User1 -> InitPage : Click create room button.
InitPage -> RoomManager : Request create unique room number with user uuid.
RoomManager -> RestAPIManager : Request create unique room number with user uuid.
RestAPIManager -> RoomService : HTTP Request(Request create unique room number with user uuid)
RoomService -> RoomService : Create room number
RoomService -> RoomDB : Save unique number and matched user id.
RoomService -> RestAPIManager : Reply unique room number.
RestAPIManager -> RoomManager : Reply unique room number.
RoomManager -> InitPage : Reply unique room number.
InitPage -> MainPage : Move main page.
MainPage -> User1 : Show main page and Toast unique room number.

User1 -> User2 : Give room number.

User2 -> InitPage : Click join room button with room number.
InitPage -> RoomManager : Request join room with room number.
RoomManager -> RestAPIManager : Request join room with room number.
RestAPIManager -> RoomService : HTTP Requset(Request join room with room number)
RoomService -> RoomDB : Search info(members id) with room number.
RoomService -> RestAPIManager : Reply info(members id)
RestAPIManager -> RoomManager : Reply info(members id)
RoomManager -> InitPage : Reply info(members id)
InitPage -> MainPage : Move main page(with members id)

MainPage -> RoomManager : Request get members info with member id.
RoomManager -> RestAPIManager : Request get members info with member id.
RestAPIManager -> RoomService : HTTP Request(Request get members info with member id)
RoomService -> MembersDB : Search member info with member id(unique)
MembersDB -> RoomService : Reply members info(state...)
RoomService -> RestAPIManager : Reply members info(state...)
RestAPIManager -> RoomManager : Reply members info(state...)
RoomManager -> MainPage : Reply members info(state...)
MainPage -> MainPage : Change main page ui.
@enduml