@startuml
title Notify State Changed
NotificationService -> PushServer : Request to send notifications for group members
PushServer -> RestAPIManager : Receive notification
RestAPIManager -> AppBloc : Get UserStateManager
RestAPIManager -> UserState : Parse json to user state
RestAPIManager -> UserStateRepository : Update User state
UserStateRepository -> UserStateRepository : Save User state
UserStateRepository -> UserStateManager : Update User state
UserStateManager -> UserState : Check receivable state
UserStateManager -> UserState : Show notification
UserStateManager -> StreamBuilder : Add User state to Stream Sink
StreamBuilder -> MainUI : Update UI
MainUI -> User : Shows changed state
@enduml