@startuml
title Generate Password
User -> MainUI : Make a room
MainUI -> UserStateManager : Make a room
UserStateManager -> UserStateProxy : Make a room
UserStateProxy -> RoomManager : Get RoomManager
UserStateProxy -> RoomManager : Make a room
RoomManager -> UUIDGenerator : Generate UUID
RoomManager -> UserDBManager : Search current UUID
RoomManager -> UserDBManager : Save current UUID
@enduml