@startuml
title Generate Password
User -> MainUI : Make a room
MainUI -> UserStateManager : Make a room
UserStateManager -> RestAPIManager : Make a room
RestAPIManager -> RoomManager : Get RoomManager
RestAPIManager -> RoomManager : Make a room
RoomManager -> UUIDGenerator : Generate UUID
RoomManager -> UserDBManager : Search current UUID
RoomManager -> UserDBManager : Save current UUID
@enduml