@startuml
title Login Fail
User  -> LoginPage : Enter ID/PW.
LoginPage -> LoginManager : Send ID/PW.
LoginManager -> AuthServer : Checking Authentication.
AuthServer -> LoginManager : Reply Authentication Reseult(PASS)
LoginManager -> LoginPage : Send Result.
LoginPage -> User : Toast popup "Login FAIL"
@enduml