@startuml
title Login Success
User  -> LoginPage : Enter ID/PW.
LoginPage -> LoginManager : Send ID/PW.
LoginManager -> AuthServer : Checking authentication.
AuthServer -> LoginManager : Reply authentication reseult(PASS)
LoginManager -> LoginPage : Send result.
LoginPage -> InitPage : Move init page.
InitPage -> User : Show init page.
@enduml