@startuml
title State Change
User -> MainUI : Change User state
MainUI -> UserStateManager : Update User state
UserStateManager -> UserStateRepository : Save User state
UserStateRepository -> UserState : Get User state info
UserStateRepository -> UserStateRepository : Save User state to local DB
UserStateRepository -> RestAPIManager : Save User state to remote DB
RestAPIManager -> RoomService : Save User state
RoomService -> MembersDB : Save User state
RoomService -> RoomDB : Get group members info
RoomService -> NotificationService : Notify User state changed

@enduml