@startuml
title State Change
User -> MainUI : Change User state
MainUI -> UserStateManager : Update User state
UserStateManager -> MainUI : Update UI 
UserStateManager -> UserStateManager : Save User state
UserStateManager -> NotificationService : Request notification for group members
NotificationService -> GroupManager : Get group members info
GroupManager -> UserDBManager : Get group members info
@enduml